### ISSUE TITLE
Warning when using mocked methods

### ISSUE THREAD

**Issue by pjlsergeant** [Test-Workflow/Mock-Quick#16]
perl -MPath::Class -MMock::Quick -e'my $x = qobj(foo => sub { print "My file is $_[1]" }); $x->foo( file(".") );'
    Argument "." isn't numeric in numeric eq (==) at /Users/pjlsergeant/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Mock/Quick/Util.pm line 44.

https://github.com/exodist/Mock-Quick/blob/master/lib/Mock/Quick/Util.pm#L44

**Comment by exodist** [comment]
There is a bug in your code, you should use qmeth instead of sub to add a custom sub to the object:

```perl -MPath::Class -MMock::Quick -e'my $x = qobj(foo => qmeth { print "My file is $_[1]" }); $x->foo( file(".") );'```

that said, the warning still occurs and needs to be fixed.
